### ISSUE TITLE
Title: Failed to Load Speech Detection Module

### ISSUE THREAD

**Issue by tinokingstone** [ai-ng/swift#14]
## Description
We're currently experiencing an issue where the speech detection module fails to load properly. This is causing the voice activity detection (VAD) functionality to be unavailable, which significantly impacts the user experience of our application.

## Steps to Reproduce
1. Launch the application
2. Attempt to use any feature that requires speech detection
3. Observe that the speech detection fails to initialize

## Expected Behavior
The speech detection module should load successfully, allowing users to interact with voice-activated features.

## Actual Behavior
The speech detection module fails to load, rendering voice-activated features unusable.

## Impact
This issue is critical as it affects a core functionality of our application. Users are unable to use voice-activated features, which significantly degrades the user experience.

Please investigate and provide any insights or potential solutions. Let me know if you need any additional information or clarification.

**Comment by n1ckoates** [comment]
Hi there - what OS and browser are you getting that error on?

**Comment by n1ckoates** [comment]
Closing this - feel free to re-open if anyone can reproduce this with more information.
