### ISSUE TITLE
" Voice Synthesis Failed" after my vercel project was up and running for 10 mins...

### ISSUE THREAD

**Issue by michael7908** [ai-ng/swift#2]
I got 2 free API keys from Groq and Cartesia.

Maybe that is the root cause? The free API keys don't last long...

**Comment by ASSALOCKE** [comment]
I Have the same problem

**Comment by n1ckoates** [comment]
"Voice Synthesis Failed" means the Cartesia request threw an error. You should be able to see a more detailed error in Vercel logs.

**Comment by n1ckoates** [comment]
Closing this because it doesn't seem to be an issue with the project itself.
