### ISSUE TITLE
multi-language tts

### ISSUE THREAD

**Issue by Gitcqs** [ai-ng/swift#4]
I see that it can accept multi-language input (Whisper) but multi-language output (tts) only supports English. Is there any tts product that supports automatic multi-language?

**Comment by n1ckoates** [comment]
Cartesia has [an alternate model](https://docs.cartesia.ai/getting-started/available-models) which supports more languages, but it's in alpha and has some issues, so we decided to just use their English model.

You can fork the project and change `sonic-english` to `sonic-multilingual` on [line 79 of `/api/api/route.ts`](https://github.com/ai-ng/swift/blob/main/app/api/route.ts#L79) if you want to!
